# .github/workflows/deploy.yml
name: Deploy to Aliyun OSS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. 安装 Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # 你可以根据需要调整版本

      - name: Update Hugo modules
        run: hugo mod get -u      # 新增此步骤，更新主题依赖

      # 2. 使用 Hugo 构建站点，生成 public 目录
      - name: Build with Hugo
        run: hugo --minify

      # 3. 配置阿里云 OSS 上传工具
      - name: Setup ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-wuhan-lr.aliyuncs.com"
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}

      # 4. 将生成的 public 目录同步到 OSS
      - name: Sync public to OSS
        run: |
          ossutil cp -r -u public/ oss://hextra-ai-insight-daily-hk/ --force
